### PR TITLE
Set default selection on xsel/xclip to clipboard

### PR DESCRIPTION
**Pull request by uberspot**
That way you can just ctrl+v the resulting imgur url. Seems more natural.

### CODE REVIEW

**Comment by tremby** [comment]
For you, perhaps. I find the X selection more natural to use.

Perhaps consider aliasing `imgur` to `imgur; xsel | xsel -b`?

**Comment by tremby** [comment]
Also no need for the added `-i` arguments in your patch.

**Comment by uberspot** [comment]
On my box xsel/xclip didn't copy to my primary clipboard though. 
Middle click just shows me things I explicitly copy with ctrl+c. Maybe it's some weird arch linux specific config somewhere(?).
I've modified it locally so if you don't want it, do close the pull request. 👍

**Comment by tremby** [comment]
Does the alias I suggested do what you are looking for?

**Comment by uberspot** [comment]
`imgur; xsel -o | xsel -b` and `imgur; xclip -o | xclip -selection clipboard` do the trick. Thanks, it might be useful to document this in the readme. 👍

**Comment by tremby** [comment]
Thanks for confirming. I'll leave it as-is for now. If others want the same feature they may find this thread or may request it, and I'll consider adding an option if it's popular or even switching the default if I'm significantly in the minority.

Thanks!

**Comment by tremby** [comment]
As of 4a4dcc1 you can set environment variables to give options to the clipboard programs, so there wouldn't be a need for a wrapper script in this case any more.

**Pull request closed without merging**
