### PR TITLE
Added a progress bar

### PR DESCRIPTION
**Pull request by Tormen**
The progress-bar really makes sense with todays huge photo files.
Otherwise script just sits there and one does not know if this is good or bad.

      Added progress-bar output to curl
      Added DBG variable to (manually) turn on/off DBG output.
      Added TEMPFILE (necessary for progress-bar output).
      Added cleanup hook to auto-cleanup the TEMPFILE even if interrupted with CTRL-C.

### CODE REVIEW

**Comment by tremby** [comment]
I've only had a brief look so far. For me to consider merging this:

- Fix your commit message. See [what tpope says about it](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- You have a second commit which is just a fixup to the first; combine them.
- Your indentation is a mess; fix it. This project uses tabs.
- There appear to be a lot of changes in your patch which are nothing to do with the proposed extra functionality. Extra newlines here and there, a case and name change of a variable, etc. Tidy this up. Any necessary refactoring should be a separate commit before your feature is added.

I haven't studied your code yet, but I see that you're writing temporary files. I don't like the idea of this -- is there another way? What are they for? Is what you have done any different than just removing the `2>/dev/null` lines from the `upload` calls, and replacing `-s` with `--progress-bar` in the `curl` call in the `upload` function?

**Comment by Tormen** [comment]
Hi,

Thanks for your feedback. Will bare that in mind for my next pull
request on github ;)

The temporary file is necessary because you need to specify a -o to curl
in order for --progress-bar to work.

Tormen

**Comment by tremby** [comment]
Why "next" pull request? I certainly won't merge this unless you tidy it up.

> The temporary file is necessary because you need to specify a -o to curl in order for --progress-bar to work.

Not true. What I suggested above works for me. See here: https://github.com/tremby/imgur.sh/commit/357d96a128cc1685bae99c2d1e07bf5e65dc1d48

Does this not work with your version of curl? What version is that?

**Comment by Tormen** [comment]
On 26/04/17 20:34, Bart Nagel wrote:
> Why "next" pull request? I certainly won't merge this unless you tidy it up.
>
>> The temporary file is necessary because you need to specify a -o to curl in order for --progress-bar to work.
> Not true. 
Well. Let's see about that my young padowan ;)

> What I suggested above works for me. See here: https://github.com/tremby/imgur.sh/commit/357d96a128cc1685bae99c2d1e07bf5e65dc1d48
>
> Does this not work with your version of curl? What version is that?
It is the first thing I tried ;)

curl --progress-bar -H "Authorization: Client-ID
<put-your-client-id-here>" -H "Expect: " -F "image=@/tmp/199635.jpe"
https://api.imgur.com/3/image.xml

(with <put-your-client-id-here> replaced with a valid imgur.com
client-id) gives me NO progress bar.

curl 7.53.1 (x86_64-pc-linux-gnu) libcurl/7.53.1 OpenSSL/1.0.2k
zlib/1.2.11 libpsl/0.17.0 (+libicu/58.2) libssh2/1.8.0

man curl

secion PROGRESS METER states for me:

 If you want a progress meter for HTTP POST or PUT requests, you need to
redirect the response output to a file, using shell redirect (>), -o,
       --output or similar.

And as you are uploading something here + I did not see any output, I
figured to try -o and voila the progress bar appeared.

So: No, this does not work with my version of curl ;)

What's your version of curl ?

**Comment by tremby** [comment]
> curl --progress-bar -H "Authorization: Client-ID <put-your-client-id-here>" -H "Expect: " -F "image=@/tmp/199635.jpe" https://api.imgur.com/3/image.xml
> 
> (with <put-your-client-id-here> replaced with a valid imgur.com client-id) gives me NO progress bar.

Yes, this is not surprising, and you gave the reasons yourself in your message. The section of the manual you quoted says:

> you need to redirect the response output to a file, using shell redirect (>), -o, --output or similar

My version *is* doing this. The stdout is being captured in a variable via for example `response=$(upload "$file")`, and that's exactly the same as far as curl is concerned as redirection via the shell or curl's output to file options. The reason curl requires this for the progress bar to display is that otherwise the progress bar will be being printed to your terminal interleaved with the actual response output.

Try your command above in a capture-to-variable, like `whatever=$(curl --progress-bar -H "Authorization: Client-ID <put-your-client-id-here>" -H "Expect: " -F "image=@/tmp/199635.jpe" https://api.imgur.com/3/image.xml)` and you'll see the progress bar.

Did you actually try my version of the file I linked to, or not? It works for me with both

```
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

and

```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by Tormen** [comment]
Ah d*mn it, you are right.

Thanks for hangin' in there with me!

Yes of course.

My mistake: I did try --progress-bar -s -H in your version, then I
removed the -s but also took the curl out of the ` ` quotes.
Argh.

Ok. Then all good. Perfect solution :)

**Comment by tremby** [comment]
OK, I'm going to leave this open as a reminder to myself, but obviously go with the simpler version. I'm going to let it sit for a while, while I use it as I normally do, so I can decide whether this should be hidden behind an option or not, and if so, whether it should be default or opt-in.

Thanks for the idea.

**Comment by tremby** [comment]
I've decided I don't like it. The progress bar zooms to completion as the upload finishes, and I then still have to wait an unpredictable amount of time for completion. If we could give a progress bar for the entire process it may be worthwhile, but I don't think that's possible.

**Pull request closed without merging**
